services:

  # Required Symfony Services
  http_kernel:
    class: Symfony\Component\HttpKernel\HttpKernel
    arguments:
      - '@lean.event_dispatcher'
      - '@lean.controller_resolver'
      - '@lean.request_stack'
      - '@lean.argument_resolver'

  # Standard Symfony Services
  templating:
    class: LeanSymfony\Bundle\FrameworkBundle\Templating\TemplateEngine
    arguments: [['@templating.engine.php','@templating.engine.twig']]

  # Lean Symfony Framework Services
  lean.container_factory:
    class: LeanSymfony\Bundle\FrameworkBundle\Container\DIContainerFactory

  lean.container:
      class:   DI\Container
      factory: 'lean.container_factory:createDIContainer'
      arguments: ['@service_container']

  lean.logger.console_handler:
    class: Monolog\Handler\BrowserConsoleHandler

  lean.logger:
    class: Monolog\Logger
    arguments: ['Lean Symfony']
    calls:
      - [pushHandler, ['@lean.logger.console_handler']]

  lean.event_dispatcher:
    class: LeanSymfony\Component\EventDispatcher\EventDispatcher
    arguments: ['@lean.logger']

  lean.controller_resolver:
    class: LeanSymfony\Bundle\FrameworkBundle\Controller\ControllerResolver
    arguments: ['@lean.container','@lean.logger']

  lean.request_stack:
    class: Symfony\Component\HttpFoundation\RequestStack

  lean.argument_resolver:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver

  # Templating related services
  twig:
    class: Twig_Environment
    arguments: ['@twig.loader']
  twig.loader:
    class: Twig_Loader_Filesystem
    arguments: ['%kernel.root_dir%/Resources/views']
  templating.engine.php:
    class: Symfony\Component\Templating\PhpEngine
    arguments: ['@templating.name_parser','@templating.loader']
  templating.engine.twig:
    class: LeanSymfony\Bundle\FrameworkBundle\Templating\TwigEngine
    arguments: ['@twig','@templating.name_parser']
  templating.name_parser:
    class: Symfony\Component\Templating\TemplateNameParser
  templating.loader:
    class: Symfony\Component\Templating\Loader\FilesystemLoader
    arguments: [['%kernel.root_dir%/Resources/views/%%name%%']]
