services:

  # Required Symfony Services
  http_kernel:
    class: Symfony\Component\HttpKernel\HttpKernel
    arguments:
      - '@lean.event_dispatcher'
      - '@lean.controller_resolver'
      - '@lean.request_stack'
      - '@lean.argument_resolver'

  # Lean Symfony Framework Services
  lean.container_factory:
    class: LeanSymfony\Bundle\FrameworkBundle\Container\DIContainerFactory

  lean.container:
      class:   DI\Container
      factory: 'lean.container_factory:createDIContainer'

  lean.logger.console_handler:
    class: Monolog\Handler\BrowserConsoleHandler

  lean.logger:
    class: Monolog\Logger
    arguments: ['Lean Symfony']
    calls:
      - [pushHandler, ['@lean.logger.console_handler']]

  lean.event_dispatcher:
    class: LeanSymfony\Component\EventDispatcher\EventDispatcher
    arguments: ['@lean.logger']

  lean.controller_resolver:
    class: LeanSymfony\Bundle\FrameworkBundle\Controller\ControllerResolver
    arguments: ['@lean.container','@lean.logger']

  lean.request_stack:
    class: Symfony\Component\HttpFoundation\RequestStack

  lean.argument_resolver:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver
